In [68]:
import pandas as pd
from pandas import DataFrame
import warnings
import numpy as np
import ast
warnings.filterwarnings('ignore')

In [69]:
df = pd.DataFrame(pd.read_csv('../Data/movieinfo.csv'))

In [70]:
df.head()

,movieId,title,overview,ytlink,poster,featcrew,budget,revenue,runtime,lang,keywords,year
0,1,Toy Story,"Led by Woody, Andy's toys live happily in his ...",https://www.youtube.com/watch?v=tN1A2mVnrOM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'John Lasseter': 'Director', 'Alec Sokolow': ...","$30,000,000.00","$373,554,033.00",1h 21m,English,"[martial arts, jealousy, toy, boy, friendship,...",1995
1,2,Jumanji,When siblings Judy and Peter discover an encha...,https://www.youtube.com/watch?v=3LPANjHlPxo,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Joe Johnston': 'Director', 'Chris van Allsbu...","$65,000,000.00","$262,797,249.00",1h 44m,English,"[giant insect, board game, jungle, disappearan...",1995
2,3,Grumpier Old Men,A family wedding reignites the ancient feud be...,https://www.youtube.com/watch?v=rEnOoWs3FuA,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Mark Steven Johnson': 'Characters, Writer', ...",-,-,1h 41m,English,"[fishing, old man, best friend, duringcreditss...",1995
3,4,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",https://www.youtube.com/watch?v=j9xml1CxgXI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Terry McMillan': 'Novel, Screenplay', 'Fores...","$16,000,000.00","$81,452,156.00",2h 7m,English,"[based on novel or book, interracial relations...",1995
4,5,Father of the Bride Part II,Just when George Banks has recovered from his ...,https://www.youtube.com/watch?v=ltwvKLnj1B4,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Charles Shyer': 'Director', 'Albert Hackett'...",-,"$76,578,911.00",1h 46m,English,"[parent child relationship, baby, midlife cris...",1995

In [71]:
lst_col = 'keywords'

In [72]:
x = df.assign(**{lst_col:df[lst_col].str.split(',')})

In [73]:
df = pd.DataFrame({col:np.repeat(x[col].values, x[lst_col].str.len())for col in x.columns.difference([lst_col])}).assign(**{lst_col:np.concatenate(x[lst_col].values)})[x.columns.tolist()]

In [74]:
df = df.drop(df.columns[[2,3, 4, 5, 6, 7, 8, 9, 11]], axis=1)

In [75]:
df = df.drop(df.columns[[1]], axis=1)

In [76]:
df

       movieId       keywords
0            1  [martial arts
1            1       jealousy
2            1            toy
3            1            boy
4            1     friendship
...        ...            ...
74295   193587  [supernatural
74296   193587          mafia
74297   193587    super power
74298   193587         anime]
74299   193609              -

[74300 rows x 2 columns]

In [77]:
df['keywords'] = df['keywords'].str.strip('[')
df['keywords'] = df['keywords'].str.strip(']')
df['keywords'] = df['keywords'].str.strip('""')
df['keywords'] = df['keywords'].str.strip('"')

In [78]:
df = df[df.keywords != "-"]

In [79]:
from pandas.api.types import is_string_dtype
is_string_dtype(df['keywords'])

True

In [96]:
df = df[~df['keywords'].str.contains('"')]

In [97]:
df.to_csv('../Data/movie_keys.csv', index=False)