In [38]:
import datetime as dt
from datetime import datetime
import pandas as pd
import numpy as np
import uuid

In [121]:
df = pd.DataFrame(pd.read_csv('../Data/reviews.csv'))

In [122]:
df['date'] = uuid.uuid4()
df['id'] = uuid.uuid4()

In [123]:
df

,id,title,rating,text,movieId,timestamp,date,userId
0,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,1,964982703,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
1,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,3,964981247,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
2,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,6,964982224,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
3,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,47,964983815,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
4,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,50,964982931,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
5,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,70,964982400,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
6,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,101,964980868,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
7,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,110,964982176,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
8,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,151,964984041,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
9,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,157,964984100,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
10,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,163,964983650,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
11,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,216,964981208,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
12,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,223,964980985,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
13,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,231,964981179,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
14,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,235,964980908,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
15,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,260,964981680,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
16,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,296,964982967,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
17,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,316,964982310,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
18,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,333,964981179,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
19,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,349,964982563,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
20,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,356,964980962,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
21,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,362,964982588,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
22,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,367,964981710,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
23,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,423,964982363,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
24,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,441,964980868,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
25,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,457,964981909,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
26,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,480,964982346,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
27,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,500,964981208,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
28,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,527,964984002,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
29,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,543,964981179,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,1
...,...,...,...,...,...,...,...,...
100806,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,150401,1479543210,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100807,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,152077,1493845817,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100808,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,152081,1493846503,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100809,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,152372,1493848841,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100810,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,155064,1493848456,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100811,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,156371,1479542831,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100812,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.5,NaN,156726,1493848444,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100813,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,157296,1493846563,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100814,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,158238,1479545219,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100815,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,158721,1479542491,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100816,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,158872,1493848024,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100817,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,158956,1493848947,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100818,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,159093,1493847704,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100819,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,160080,1493848031,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100820,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,2.5,NaN,160341,1479545749,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100821,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.5,NaN,160527,1479544998,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100822,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,160571,1493848537,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100823,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,160836,1493844794,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100824,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,161582,1493847759,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100825,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,161634,1493848362,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100826,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,162350,1493849971,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100827,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,163937,1493848789,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100828,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.5,NaN,163981,1493850155,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100829,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,164179,1493845631,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100830,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,166528,1493879365,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100831,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,4.0,NaN,166534,1493848402,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100832,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,168248,1493850091,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100833,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,168250,1494273047,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100834,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,5.0,NaN,168252,1493846352,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610
100835,92705cff-924e-476c-8d0c-8f4b6dd811be,NaN,3.0,NaN,170875,1493846415,fc65e3e6-ce4d-46f3-868e-3d0394e55fc6,610

In [124]:
for i in range(len(df)):
    df['id'][i] = uuid.uuid4()
    dt_object = datetime.fromtimestamp(df["timestamp"][i])
    df["date"][i] = dt_object.strftime("%F")

/home/reddwarf/environments/MovieSocialApp/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/reddwarf/environments/MovieSocialApp/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [125]:
df["text"] = "Blank"

In [126]:
df["title"] = "N/A"

In [127]:
cols = ['id', 'title', 'rating', 'text', 'movieId', 'timestamp', 'date', 'userId']

In [128]:
df = df[cols]

In [129]:
df

,id,title,rating,text,movieId,timestamp,date,userId
0,caaa367f-f88d-4011-b7cd-1ee9419a54d5,N/A,4.0,Blank,1,964982703,2000-07-30,1
1,2492be8a-927b-41b6-a665-80d6c5db86eb,N/A,4.0,Blank,3,964981247,2000-07-30,1
2,7a2b2887-76a1-4945-964d-1bd8d246fc5d,N/A,4.0,Blank,6,964982224,2000-07-30,1
3,2b19881e-ba46-458e-85b2-8c02e5d7ad17,N/A,5.0,Blank,47,964983815,2000-07-30,1
4,c6bbf4c1-955e-4f17-bce6-d0b576c39b2f,N/A,5.0,Blank,50,964982931,2000-07-30,1
5,0d417491-109e-4572-894a-692cd14dcb62,N/A,3.0,Blank,70,964982400,2000-07-30,1
6,79af9f04-7f43-43f7-9061-77fe299d2912,N/A,5.0,Blank,101,964980868,2000-07-30,1
7,daed7ee3-8b77-4f2b-8f9b-82178bf2d8a8,N/A,4.0,Blank,110,964982176,2000-07-30,1
8,66790730-8942-4da1-b6cd-d051250987b1,N/A,5.0,Blank,151,964984041,2000-07-30,1
9,69f3dda4-1dd6-44a7-b5f2-5a539cdd8f76,N/A,5.0,Blank,157,964984100,2000-07-30,1
10,37c363e4-4080-483d-ad0d-1e7e1a90bd2c,N/A,5.0,Blank,163,964983650,2000-07-30,1
11,764de259-c904-4503-9ead-6c83417b13f6,N/A,5.0,Blank,216,964981208,2000-07-30,1
12,0d96da1d-9c83-4ab4-8166-097d71adb3d5,N/A,3.0,Blank,223,964980985,2000-07-30,1
13,b5badb89-9bad-4f65-b539-769a858b995a,N/A,5.0,Blank,231,964981179,2000-07-30,1
14,49bc969c-7ad1-4706-9786-d4abcc0575d3,N/A,4.0,Blank,235,964980908,2000-07-30,1
15,85b29f1c-4e5c-4291-8a85-f0e377d19f69,N/A,5.0,Blank,260,964981680,2000-07-30,1
16,545e6b93-e27c-4d6d-8933-bc65d2f2278f,N/A,3.0,Blank,296,964982967,2000-07-30,1
17,c1129432-3a69-44e1-aef0-84d199da4053,N/A,3.0,Blank,316,964982310,2000-07-30,1
18,d9cc7cd9-1415-41e1-91c4-8bdf9f12aa6f,N/A,5.0,Blank,333,964981179,2000-07-30,1
19,d80b7b59-f279-4ec9-87cb-5f0008dd505c,N/A,4.0,Blank,349,964982563,2000-07-30,1
20,d1241608-91a2-454f-b5ac-a157c9fc33bf,N/A,4.0,Blank,356,964980962,2000-07-30,1
21,b290af07-1347-441e-b6d9-0c8e5590d780,N/A,5.0,Blank,362,964982588,2000-07-30,1
22,43b34ecc-84d3-4add-80ba-ca76ce9bfe29,N/A,4.0,Blank,367,964981710,2000-07-30,1
23,fcabbe2a-4431-4a89-90c0-32359dae6363,N/A,3.0,Blank,423,964982363,2000-07-30,1
24,dc1a1318-9ba3-445c-9819-4f3d70a94f01,N/A,4.0,Blank,441,964980868,2000-07-30,1
25,0ea5efa9-2d9c-4358-bc41-607a3f0d76e3,N/A,5.0,Blank,457,964981909,2000-07-30,1
26,f472a398-ea61-4ec6-ae82-a96f9dbe1e4f,N/A,4.0,Blank,480,964982346,2000-07-30,1
27,a48c23c1-2c3c-4b38-81bf-9ecfa6581423,N/A,3.0,Blank,500,964981208,2000-07-30,1
28,5c3e2139-9391-4d94-8c51-b836b1346bd6,N/A,5.0,Blank,527,964984002,2000-07-30,1
29,3302ca73-6140-40cb-baf3-1ace64ef354b,N/A,4.0,Blank,543,964981179,2000-07-30,1
...,...,...,...,...,...,...,...,...
100806,aa43e6fe-422a-4a0a-b229-5b73ce2c473c,N/A,3.0,Blank,150401,1479543210,2016-11-19,610
100807,6127b39a-ecfb-4909-8943-c42cc2375ff5,N/A,4.0,Blank,152077,1493845817,2017-05-04,610
100808,3412fed1-bf72-4d49-abe1-24238aa3cb73,N/A,4.0,Blank,152081,1493846503,2017-05-04,610
100809,3c20d381-b0c1-494c-8262-1b1ac8fad044,N/A,3.5,Blank,152372,1493848841,2017-05-04,610
100810,ed6d6e4b-1e02-4897-8bad-4885e35aad59,N/A,3.5,Blank,155064,1493848456,2017-05-04,610
100811,fb34e682-108d-466a-83ff-0340934028f0,N/A,5.0,Blank,156371,1479542831,2016-11-19,610
100812,dcfa5dea-f668-4599-919f-f4a29990598c,N/A,4.5,Blank,156726,1493848444,2017-05-04,610
100813,11c2b48e-c317-41d1-a819-8cec3f900068,N/A,4.0,Blank,157296,1493846563,2017-05-04,610
100814,7010d6e7-a512-4245-b1b3-44bd9c15c83a,N/A,5.0,Blank,158238,1479545219,2016-11-19,610
100815,7842a3ca-17f3-423b-b78d-81771fdb295d,N/A,3.5,Blank,158721,1479542491,2016-11-19,610
100816,0fea5908-75b1-4727-8611-a71ea3ed119c,N/A,3.5,Blank,158872,1493848024,2017-05-04,610
100817,5c7f4318-7cdf-42f8-acf0-329a79d1788c,N/A,3.0,Blank,158956,1493848947,2017-05-04,610
100818,d44d1401-2c36-497a-b47a-d1867a8c1e3d,N/A,3.0,Blank,159093,1493847704,2017-05-04,610
100819,24f7104c-b53b-41dc-8baa-fc9c40419111,N/A,3.0,Blank,160080,1493848031,2017-05-04,610
100820,093c32d3-f6c1-4cc7-9514-f37b6b9f33f7,N/A,2.5,Blank,160341,1479545749,2016-11-19,610
100821,23abd30e-b7ea-464c-8dbe-a9f005ed6bd2,N/A,4.5,Blank,160527,1479544998,2016-11-19,610
100822,464a5e92-7fcb-47fa-ae59-8b96780cda1f,N/A,3.0,Blank,160571,1493848537,2017-05-04,610
100823,2244af0f-a045-4cb9-9ff0-dc3618ace480,N/A,3.0,Blank,160836,1493844794,2017-05-04,610
100824,bf72166b-a92d-467f-8cda-3a36a59ff485,N/A,4.0,Blank,161582,1493847759,2017-05-04,610
100825,ba474fda-dd3c-46fe-be7f-3e370dc71494,N/A,4.0,Blank,161634,1493848362,2017-05-04,610
100826,0d975602-3d01-4dda-8741-b8dc1bfb5f50,N/A,3.5,Blank,162350,1493849971,2017-05-04,610
100827,1f8245e6-b3cf-4e7a-96d2-517dfc3d048f,N/A,3.5,Blank,163937,1493848789,2017-05-04,610
100828,74eed8a7-9631-4e35-b0e9-8c64a3e7298c,N/A,3.5,Blank,163981,1493850155,2017-05-04,610
100829,c4b95a43-f619-4309-9a3e-e768a57a3194,N/A,5.0,Blank,164179,1493845631,2017-05-04,610
100830,be44dda3-f663-405c-8d11-28d116061b39,N/A,4.0,Blank,166528,1493879365,2017-05-04,610
100831,cda58b74-7467-46d9-9c11-148e088c80a1,N/A,4.0,Blank,166534,1493848402,2017-05-04,610
100832,c3d0d4ff-808f-45e6-a0a6-4ffdcbefd79c,N/A,5.0,Blank,168248,1493850091,2017-05-04,610
100833,fb832147-96c4-44a1-83c3-59c64ff21094,N/A,5.0,Blank,168250,1494273047,2017-05-08,610
100834,fc67091d-3e8a-4919-9008-e42bd31803a1,N/A,5.0,Blank,168252,1493846352,2017-05-04,610
100835,0a56d48f-6b83-46a2-a5ba-4b5802b91d6b,N/A,3.0,Blank,170875,1493846415,2017-05-04,610

In [131]:
df.to_csv('../Data/reviews.csv', index=False)

In [19]:
dffilm = pd.DataFrame(pd.read_csv('../Data/movieinfo.csv'))
dfrating = pd.DataFrame(pd.read_csv('../Data/ratings.csv'))

In [20]:
dfrating.head()

   rating  userId  movieId
0     4.0       1        1
1     4.0       1        3
2     4.0       1        6
3     5.0       1       47
4     5.0       1       50

In [21]:
mean_movies_rat = dfrating.groupby(['movieId']).agg({'rating': np.mean}).reset_index()

In [22]:
mean_movies_rat.head()

   movieId    rating
0        1  3.920930
1        2  3.431818
2        3  3.259615
3        4  2.357143
4        5  3.071429

In [25]:
df3 = pd.merge(dffilm, mean_movies_rat, left_on='movieId', right_on='movieId', how='left')

In [26]:
df3

,movieId,title,overview,ytlink,poster,featcrew,budget,revenue,runtime,lang,keywords,year,rating
0,1,Toy Story,"Led by Woody, Andy's toys live happily in his ...",https://www.youtube.com/watch?v=tN1A2mVnrOM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'John Lasseter': 'Director', 'Alec Sokolow': ...","$30,000,000.00","$373,554,033.00",1h 21m,English,"[martial arts, jealousy, toy, boy, friendship,...",1995,3.920930
1,2,Jumanji,When siblings Judy and Peter discover an encha...,https://www.youtube.com/watch?v=3LPANjHlPxo,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Joe Johnston': 'Director', 'Chris van Allsbu...","$65,000,000.00","$262,797,249.00",1h 44m,English,"[giant insect, board game, jungle, disappearan...",1995,3.431818
2,3,Grumpier Old Men,A family wedding reignites the ancient feud be...,https://www.youtube.com/watch?v=rEnOoWs3FuA,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Mark Steven Johnson': 'Characters, Writer', ...",-,-,1h 41m,English,"[fishing, old man, best friend, duringcreditss...",1995,3.259615
3,4,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",https://www.youtube.com/watch?v=j9xml1CxgXI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Terry McMillan': 'Novel, Screenplay', 'Fores...","$16,000,000.00","$81,452,156.00",2h 7m,English,"[based on novel or book, interracial relations...",1995,2.357143
4,5,Father of the Bride Part II,Just when George Banks has recovered from his ...,https://www.youtube.com/watch?v=ltwvKLnj1B4,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Charles Shyer': 'Director', 'Albert Hackett'...",-,"$76,578,911.00",1h 46m,English,"[parent child relationship, baby, midlife cris...",1995,3.071429
5,6,Heat,"Obsessive master thief, Neil McCauley leads a ...",https://www.youtube.com/watch?v=14oNcFxiVaQ,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Michael Mann': 'Director, Screenplay'}","$60,000,000.00","$187,436,818.00",2h 50m,English,"[robbery, detective, obsession, chase, thief, ...",1995,3.946078
6,7,Sabrina,An ugly duckling having undergone a remarkable...,https://www.youtube.com/watch?v=twTksx_lWB4,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Sydney Pollack': 'Director', 'Barbara Benede...","$58,000,000.00",-,2h 7m,English,"[paris france, sibling relationship, chauffeur...",1995,3.185185
7,8,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",https://www.youtube.com/watch?v=-C-xXZyX2zU,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Peter Hewitt': 'Director', 'Mark Twain': 'No...",-,-,1h 37m,English,-,1995,2.875000
8,9,Sudden Death,When a man's daughter is suddenly taken during...,https://www.youtube.com/watch?v=wxur3zQJ3jU,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Peter Hyams': 'Director', 'Gene Quintano': '...","$35,000,000.00","$64,350,171.00",1h 46m,English,"[terrorist, hostage, explosive, vice president]",1995,3.125000
9,10,GoldenEye,James Bond must unmask the mysterious head of ...,https://www.youtube.com/watch?v=C4hbwwq5wlQ,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Martin Campbell': 'Director', 'Ian Fleming':...","$58,000,000.00","$352,194,034.00",2h 10m,English,"[cuba, falsely accused, secret identity, compu...",1995,3.496212
10,11,"American President, The","Widowed U.S. president Andrew Shepherd, one of...",https://www.youtube.com/watch?v=UrC75wUKoFM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Rob Reiner': 'Director', 'Aaron Sorkin': 'Sc...","$62,000,000.00","$107,879,496.00",1h 46m,English,"[the white house, usa president, new love, wid...",1995,3.671429
11,12,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,https://www.youtube.com/watch?v=HGCKrgSeXcE,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Mel Brooks': 'Director, Screenplay', 'Steve ...",-,-,1h 28m,English,"[dracula, spoof]",1995,2.421053
12,13,Balto,An outcast half-wolf risks his life to prevent...,https://www.youtube.com/watch?v=a6lGULmQdb0,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Simon Wells': 'Director', 'David Steven Cohe...",-,"$11,348,324.00",1h 18m,English,"[wolf, pet, dog-sledding race, alaska, dog, go...",1995,3.125000
13,14,Nixon,An all-star cast powers this epic look at Amer...,https://www.youtube.com/watch?v=dO2LWKpeyI8,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Oliver Stone': 'Director, Screenplay', 'Step...","$44,000,000.00","$13,681,765.00",3h 12m,English,"[washington d.c., usa president, 1970s, presid...",1995,3.833333
14,15,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",https://www.youtube.com/watch?v=zvzK7dz9qMI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Renny Harlin': 'Director', 'Robert King': 'S...","$98,000,000.00","$10,017,322.00",1h 59m,English,"[exotic island, treasure, map, ship, scalp, pi...",1995,3.000000
15,16,Casino,"In early-1970s Las Vegas, low-level mobster Sa...",https://www.youtube.com/watch?v=EJXDMwGWhoA,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Martin Scorsese': 'Director, Screenplay', 'N...","$52,000,000.00","$116,112,375.00",2h 59m,English,"[poker, casino, drug abuse, 1970s, overdose, m...",1995,3.926829
16,17,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",https://www.youtube.com/watch?v=lJrAZeP_8tA,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Ang Lee': 'Director', 'Jane Austen': 'Novel'...","$16,000,000.00","$134,582,776.00",2h 16m,English,"[bowling, based on novel or book, servant, cou...",1995,3.776119
17,18,Four Rooms,It's Ted the Bellhop's first night on the job....,https://www.youtube.com/watch?v=Rieq_TR7cV0,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Quentin Tarantino': 'Director, Writer', 'Rob...","$4,000,000.00","$4,300,000.00",1h 38m,English,"[hotel, ""new years eve"", witch, bet, hotel roo...",1995,3.700000
18,19,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",https://www.youtube.com/watch?v=YG28rBUkgf8,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Steve Oedekerk': 'Director, Screenplay', 'Ja...","$30,000,000.00","$212,385,533.00",1h 30m,English,"[africa, indigenous, human animal relationship...",1995,2.727273
19,20,Money Train,When a vengeful New York transit cop decides t...,https://www.youtube.com/watch?v=5Odo80-WFgM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Joseph Ruben': 'Director', 'Doug Richardson'...","$60,000,000.00","$77,224,232.00",1h 43m,English,"[sibling relationship, subway, new york city, ...",1995,2.500000
20,21,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,https://www.youtube.com/watch?v=yNLaTtpovys,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Barry Sonnenfeld': 'Director', 'Elmore Leona...","$30,250,000.00","$115,101,622.00",1h 45m,English,"[gambling, miami, based on novel or book, gang...",1995,3.494382
21,22,Copycat,An agoraphobic psychologist and a female detec...,https://www.youtube.com/watch?v=lsmXhM4yfU0,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Jon Amiel': 'Director', 'David Madsen': 'Scr...",-,-,2h 4m,English,"[police brutality, psychology, police operatio...",1995,3.222222
22,23,Assassins,Assassin Robert Rath arrives at a funeral to k...,https://www.youtube.com/watch?v=OOTTvrb4JZI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Lana Wachowski': 'Author, Screenplay', 'Lill...","$50,000,000.00","$30,303,072.00",2h 12m,English,"[competition, assassination, cia, bank, cat, m...",1995,3.125000
23,24,Powder,Harassed by classmates who won't accept his sh...,https://www.youtube.com/watch?v=gHl-UHu2-lM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Victor Salva': 'Director, Screenplay'}",-,-,1h 51m,English,"[dead animal, shot to death, teenage boy, held...",1995,3.125000
24,25,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",https://www.youtube.com/watch?v=UMlYWZgCIgo,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Mike Figgis': 'Director, Screenplay', ""John ...","$3,600,000.00","$49,800,000.00",1h 52m,English,"[individual, prostitute, alcohol, casino, love...",1995,3.625000
25,26,Othello,The evil Iago pretends to be friend of Othello...,https://www.youtube.com/watch?v=RAYuASqrs94,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Oliver Parker': 'Director', 'William Shakesp...",-,-,2h 3m,English,"[shakespeare, jealousy, friends, moor]",1995,3.500000
26,27,Now and Then,Waxing nostalgic about the bittersweet passage...,https://www.youtube.com/watch?v=RQLVzTtt2Ws,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Lesli Linka Glatter': 'Director', 'I. Marlen...","$12,000,000.00","$27,400,000.00",1h 40m,English,"[1970s, female friendship, coming of age, gyne...",1995,3.333333
27,28,Persuasion,This film adaptation of Jane Austen's last nov...,https://www.youtube.com/watch?v=K5K7_fqHILI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Roger Michell': 'Director', 'Jane Austen': '...",-,-,1h 44m,English,"[captain, napoleonic wars, old flame, admiral]",1995,4.227273
28,29,"City of Lost Children, The (Cité des enfants p...",A scientist in a surrealist society kidnaps ch...,https://www.youtube.com/watch?v=toH1vzAmDBI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Marc Caro': 'Director, Screenplay', 'Jean-Pi...",-,"$18,000,000.00",1h 48m,French,"[clone, dream, island, eye, dystopia, aging, f...",1995,4.013158
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao),A provincial boy related to a Shanghai crime f...,https://www.youtube.com/watch?v=mQf3Ngg2cks,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Zhang Yimou': 'Director', 'Li Xiao': 'Novel'...",-,"$2,300,000.00",1h 48m,Chinese,"[servant, cabaret, shanghai, diva, uncle, mist...",1995,3.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9712,188189,Sorry to Bother You,In an alternate present-day version of Oakland...,https://www.youtube.com/watch?v=enH3xA4mYcY,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Boots Riley': 'Director, Screenplay'}",-,-,1h 45m,English,"[slavery, satire, blood, poverty, oakland cali...",2018,4.500000
9713,188301,Ant-Man and the Wasp,Just when his time under house arrest is about...,https://www.youtube.com/watch?v=8_rTIAOohas,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Peyton Reed': 'Director', 'Gabriel Ferrari':...","$140,000,000.00","$622,674,139.00",1h 59m,English,"[insect, shrinking, sequel, superhero, based o...",2018,3.666667
9714,188675,Dogman,"Marcello, a small and gentle dog groomer, find...",https://www.youtube.com/watch?v=ewh0lBcEb2U,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Matteo Garrone': 'Director, Screenplay, Stor...",-,-,1h 43m,Italian,"[italy, robber, cocaine, revenge, dog cage]",2018,3.500000
9715,188751,Mamma Mia: Here We Go Again!,"Five years after meeting her three fathers, So...",https://www.youtube.com/watch?v=XcSMdhfKga4,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Ol Parker': 'Director, Writer', 'Catherine J...","$75,000,000.00","$167,225,525.00",1h 53m,English,"[greece, musical, sequel, greek island, afterc...",2018,4.500000
9716,188797,Tag,"For one month every year, five highly competit...",https://www.youtube.com/watch?v=kjC1zmZo30U,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Jeff Tomsic': 'Director', 'Mark Steilen': 'S...","$28,000,000.00","$75,100,000.00",1h 40m,English,"[travel, game, group of friends, based on supp...",2018,4.000000
9717,188833,The Man Who Killed Don Quixote,"Toby, a cynical advertising director finds him...",https://www.youtube.com/watch?v=CmscmzjFLdc,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Terry Gilliam': 'Director, Screenplay', 'Mig...","$19,116,000.00",-,2h 12m,English,[based on novel or book],2018,4.500000
9718,189043,Boundaries,"Single mom Laura, along with her awkward 14 ye...",https://www.youtube.com/watch?v=xf6qk93WHf0,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Shana Feste': 'Director, Writer'}",-,"$557,169.00",1h 45m,English,"[road trip, family relationships, marijuana, e...",2018,2.500000
9719,189111,Spiral,A look at the rise of anti-Semitism and assaul...,https://www.youtube.com/watch?v=5gW4TLdyuVU,https://image.tmdb.org/t/p/w300_and_h450_bestv...,{'Laura Fairrie': 'Director'},-,-,1h 18m,English,"[france, anti semitism]",2018,3.000000
9720,189333,Mission: Impossible - Fallout,"When an IMF mission ends badly, the world is f...",https://www.youtube.com/watch?v=wb49-oV0F78,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Christopher McQuarrie': 'Director, Screenpla...","$178,000,000.00","$791,017,452.00",2h 28m,English,"[paris france, london, spy, helicopter, gun, s...",2018,3.750000
9721,189381,SuperFly,Career criminal Youngblood Priest wants out of...,https://www.youtube.com/watch?v=TMy_oIOCT7s,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Director X.': 'Director', 'Alex Tse': 'Scree...","$16,000,000.00","$20,545,116.00",1h 47m,English,"[gambling, corruption, sex, famous score, nigh...",2018,2.500000
9722,189547,Iron Soldier,We don't have an overview translated in Englis...,https://www.youtube.com/watch?v=x01zeWeIHIg,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Brett Kelly': 'Director', 'David A. Lloyd': ...",-,-,1h 15m,English,"[low-budget, robot]",2010,1.000000
9723,189713,BlacKkKlansman,"Colorado Springs, late 1970s. Ron Stallworth, ...",https://www.youtube.com/watch?v=pFc6I0rgmgY,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Spike Lee': 'Director, Screenplay', 'David R...","$15,000,000.00","$48,686,605.00",2h 15m,English,"[ku klux klan, based on novel or book, biograp...",2018,2.500000
9724,190183,The Darkest Minds,After a disease kills 98% of America's childre...,https://www.youtube.com/watch?v=tN8o_E_f9FQ,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Jennifer Yuh Nelson': 'Director', 'Alexandra...","$34,000,000.00","$41,142,379.00",1h 45m,English,"[based on novel or book, dystopia, super power...",2018,3.500000
9725,190207,Tilt,TILT is a love story set against the backdrop ...,https://www.youtube.com/watch?v=UIDgk1WwABs,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Viktor Chouchkov': 'Director, Writer', 'Bori...",-,-,1h 34m,Bulgarian,-,2011,1.500000
9726,190209,Jeff Ross Roasts the Border,Roastmaster Jeff Ross explores the world surro...,https://www.youtube.com/watch?v=YZWtH24zo1M,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Jeffrey Ross': 'Director, Writer', 'Stuart M...",-,-,0h 50m,English,"[immigration, border crossing, stand-up comedy...",2017,4.000000
9727,190213,John From,Rita is fifteen and spends the summer between ...,https://www.youtube.com/watch?v=pgxBGvarJrg,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'João Nicolau': 'Director, Writer'}",-,-,1h 40m,Portuguese,"[neighbor, coming of age, summer, art]",2015,1.000000
9728,190215,Liquid Truth,"Rubens is a carefree, charismatic swimming ins...",https://www.youtube.com/watch?v=aGadgNDRomk,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Carolina Jabor': 'Director', 'Lucas Paraizo'...",-,-,1h 27m,Portuguese,[woman director],2017,1.500000
9729,190219,Bunny,"Bunny, an elderly rabbit who uses a walker, is...",https://www.youtube.com/watch?v=i-RmuzppVuM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Chris Wedge': 'Director, Writer'}",-,-,0h 7m,English,-,1998,1.000000
9730,190221,Hommage à Zgougou (et salut à Sabine Mamou),"A short tribute to Zgougou, Varda’s cat who wa...",https://www.youtube.com/watch?v=2cggCfxMEMQ,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Agnès Varda': 'Director, Writer'}",-,-,0h 2m,French,-,2002,1.000000
9731,191005,Gintama,In an era where aliens have invaded and taken ...,https://www.youtube.com/watch?v=wbZur-vYk_Q,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Yuichi Fukuda': 'Director, Screenplay'}",-,-,2h 10m,Japanese,[based on manga],2017,4.500000
9732,193565,Gintama: The Movie,Odd Jobs Gin has taken on a lot of odd work in...,https://www.youtube.com/watch?v=znod0UKwEKM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Shinji Takamatsu': 'Director', 'Akatsuki Yam...",-,-,1h 36m,Japanese,[anime],2010,3.500000
9733,193567,anohana: The Flower We Saw That Day - The Movie,A year has passed since Menma's ghostly return...,https://www.youtube.com/watch?v=BaZcfR5aEuI,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Tatsuyuki Nagai': 'Director', 'Mari Okada': ...",-,-,1h 39m,Japanese,"[love triangle, loss of loved one, friendship,...",2013,3.000000
9734,193571,Silver Spoon,Ooejo agricultural high school is located in H...,https://www.youtube.com/watch?v=b-yCzcYqH5E,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Keisuke Yoshida': 'Director', 'Hiromu Arakaw...",-,-,1h 51m,Japanese,-,2014,4.000000
9735,193573,Love Live! The School Idol Movie,The graduation of the third-year members means...,https://www.youtube.com/watch?v=atFooSDwiUE,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Yûhei Murota': 'Characters', 'Asako Nishida'...",-,-,1h 39m,Japanese,"[idol, anime]",2015,4.000000
9736,193579,Jon Stewart Has Left the Building,Celebrating Jon Stewart's decade and a half ru...,https://www.youtube.com/watch?v=1D2PAGaKioM,https://image.tmdb.org/t/p/w300_and_h450_bestv...,NaN,-,-,0h 47m,English,-,2015,3.500000
9737,193581,Black Butler: Book of the Atlantic,"Ciel learns of a ""Aurora Society"", that is rum...",https://www.youtube.com/watch?v=YFRGd6DMtjs,https://image.tmdb.org/t/p/w300_and_h450_bestv...,{'Noriyuki Abe': 'Director'},-,-,1h 40m,Japanese,[anime],2017,4.000000
9738,193583,No Game No Life: Zero,Six thousand years before Sora and Shiro were ...,https://www.youtube.com/watch?v=MQkYCxyJGEU,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Atsuko Ishizuka': 'Director', 'Jukki Hanada'...",-,-,1h 46m,Japanese,"[fantasy, based on light novel, anime]",2017,3.500000
9739,193585,Flint,A woman deals with the toxic water scandal in ...,https://www.youtube.com/watch?v=dT-Jx3dvMu0,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Bruce Beresford': 'Director', 'Josh Sanburn'...",-,-,1h 36m,English,-,2017,3.500000
9740,193587,Bungo Stray Dogs: Dead Apple,Power users around the world are suddenly comm...,https://www.youtube.com/watch?v=9YEsioTM3rE,https://image.tmdb.org/t/p/w300_and_h450_bestv...,{'Takuya Igarashi': 'Director'},-,-,1h 30m,Japanese,"[supernatural, mafia, super power, anime]",2018,3.500000
9741,193609,Andrew Dice Clay: Dice Rules,"Outrageous, misogynistic and vulgar-to-the-max...",https://www.youtube.com/watch?v=5Htf_F6Nmtg,https://image.tmdb.org/t/p/w300_and_h450_bestv...,"{'Andrew Dice Clay': 'Story, Writer', 'Jay Dub...",-,-,1h 25m,English,-,1991,4.000000

In [27]:
df3.to_csv('../Data/movieinfo.csv', index=False)